cpp-lln-lab/bidspm

- batch_download_run.m
- subfun/pmCon.m
This was apparently due to a simple mistake on my part: I had not put the right name of the condition to use in the getOption file.
I have now updated the batch_download_run file to fix this.
> fix crash on batch_download_run

- Dockerfile
- README.md
- subfun/getData.m
2 small unrelated changes:
- Dockerfile now downloads the repo from the CPP account
- getData will check the options input and add any 'missing' field: this means that this set some "empty" fields as options in case they have not been specified by the user. See issue #15
> Dockerfile and option defaults

- README.md
Also: As it is coded now if numDummies set to 0 and unzipped file already exists, does it rewrite the file anyway? If yes, it could be changed to "check if unzipped already exists, if 1 then skip".
> edit info about step1: 'Remove Dummy Scans'

- README.md
- test/test_getData.m
This is just an additional unit test to getData to make sure that it behaves appropriately when we ask it to run all the subjects of one group only.
> Add another test to getData and improve README

- src/batches/setBatchSmoothing.m
> clean setBatchSmoothing

- src/workflows/bidsSpatialPrepro.m
> typos fixed

- .all-contributorsrc
Apparently some formatting errors slipped into that JSON file. Not sure how.
> [FIX] [INFRA] contributor bot json

- src/utils/convert3Dto4D.m
will merge directly since it is a micro change
> fix not matching var name in convert3Dto4D

- src/QA/anatomicalQA.m
- src/QA/functionalQA.m
Horrible hack for get around #174 for now
but also skips QA if running octave
@CerenB let me know if that fixes your issue.
> skip QA if running octave

- .zenodo.json
To make it easy to curate authors on zenodo releases
> add zenodo.json

- .github/workflows/check_markdown.yml
- .github/workflows/check_md_links.yml
- .github/workflows/miss_hit.yml
- .travis.yml
- README.md
- switch to github action to check markdown
> [INFRA] update CI

- src/batches/setBatchReslice.m
- src/workflows/bidsResliceTpmToFunc.m
> [ENH] workflow to reslice TPMs to func also create a mask for functional data

- src/workflows/bidsCopyRawFolder.m
Not ideal in terms of implementation but might prevent from having derivative datasets with plenty of extra data in them.
> [ENH] bids copy raw filters on task of interest

- src/batches/setBatchResults.m
- src/results/returnName.m
remove the dot in file naming string
> [FIX] bidsResults montage file naming fix

- .github/workflows/run_tests.yml
Same as bnefore but on the dev branch
This will be a fun adventure...
Or not!!!
> [INFRA] create github action to run tests

- lib/utils/plot_power_spectra_of_GLM_residuals.m
- improve graphs (fix #267)
- remove fsl warning (fix #268)
- lint the file
> [FIX] fix power spectra plotting

- demos/spm_face_rep/FaceRep_getOption.m
- demos/spm_face_rep/FaceRep_getOptionResults.m
- demos/spm_face_rep/face_rep_resolution.m
- demos/spm_face_rep/models/model-faceRepetition_smdl.json
- runTests.m
- src/batches/setBatchReslice.m
- src/utils/removeSpmPrefix.m
- src/workflows/bidsResults.m
FYI to extract p values programmatically it will likely require:
- [SPM,xSPM] = spm_getSPM(varargin)
- varargout = spm_list(varargin)
> [ENH] updatre face repetition demo to run with upsampling

- src/defaults/checkOptions.m
- tests/utils/defaultOptions.m
> [FIX] change default to not close parallelization at the end of a workflow

- src/getPrefix.m
- src/utils/manageWorkersPool.m
- src/workflows/bidsResults.m
> [FIX] make sure that workflow returns to current directory upon computing results

- docs/source/index.rst
- docs/source/links_and_references.rst
> [DOC] adds link and references to other SPM material

- .github/release-drafter.yml
- cpp_spm.m
- src/utils/isZipped.m
- src/utils/removeDummies.m
- src/utils/volumeSplicing.m
- tests/tests_unit/test_volumeSplicing.m
> [REF] Refactor volume splicing

- src/defaults/checkOptions.m
- tests/utils/defaultOptions.m
> [ENH] change default to not run GLM QA

- src/infra/checkToolbox.m
- src/subject_level/convertOnsetTsvToMat.m
- src/subject_level/createConfounds.m
- src/subject_level/removeIntercept.m
> [FIX & ENH] misc

- cpp_spm.m
- src/messages/cppSpmHelp.m
> [ENH] allow to run "contrasts" and "results" from main API

- src/workflows/stats/bidsResults.m
- tests/tests_workflows/stats/test_bidsResults.m
> [FIX] use proper subject background for montage

- src/batches/stats/setBatchGroupLevelContrasts.m
- src/batches/stats/setBatchGroupLevelResults.m
- src/workflows/stats/bidsResults.m
- tests/dummyData/models/model-vislocalizer2sampleTTest_smdl.json
- tests/tests_batches/stats/test_setBatchGroupLevelContrasts.m
> [FIX] make sure 2 sample ttest can run more than one contrasts

- src/bids/checkFmriprep.m
- src/bids/generatedBy.m
- src/workflows/bidsCopyInputFolder.m
- tests/tests_bids/test_checkFmriprep.m
> [FIX] set minimum compatible fmriprep version

- src/subject_level/saveRoiGlmSummaryTable.m
- src/workflows/roi/bidsRoiBasedGLM.m
- tests/tests_subject_level/test_saveRoiGlmSummaryTable.m
- tests/tests_workflows/stats/test_bidsRoiBasedGLM.m
> [FIX] add guard clauses to run ROI based analysis only when requested

- .github/dependabot.yml
- .github/workflows/run_system_tests_matlab.yml
- .github/workflows/run_system_tests_octave.yml
- .github/workflows/run_tests_matlab.yml
- .github/workflows/run_tests_octave.yml
- also adds a dependabot config
> [DEP] update bids matlab

- scripts/reslice_mid_brain.m
- src/batches/preproc/setBatchSmoothingAnat.m
- src/defaults/setRenamingConfig.m
- src/workflows/lesion/bidsLesionAbnormalitiesDetection.m
> [ENH] use CSF for lesion detection and rename output of lesion detection

- src/batches/preproc/setBatchSTC.m
- tests/tests_batches/preproc/test_setBatchSTC.m
> related to #763 and testing through CI if the patch breaks things (reopened)

- .github/workflows/validate_cff.yml
- CITATION.cff
- README.md
> [MNT] use github action to validate citation cff

- src/workflows/stats/bidsResults.m
- tests/tests_workflows/stats/test_bidsResults.m
> [FIX] throw warning when no results are asked

- src/infra/getEnvInfo.m
> [FIX] make collecting of OS version on windows more robust

- src/workflows/stats/bidsResults.m
- tests/tests_bids_model/test_bidsModel.m
> [DOC] add auto label of activation info

- src/subject_level/specifyDummyContrasts.m
- src/utils/getRegressorIdx.m
- tests/dummyData/models/model-bug825_smdl.json
- tests/tests_subject_level/test_specifyDummyContrasts.m
> [FIX] use glob patterns to define dummy contrasts

- bidspm.m
- src/IO/getData.m
- src/infra/checkToolbox.m
- src/messages/noRoiFound.m
- src/reports/boilerplate.m
- tests/tests_infra/test_checkToolbox.m
- tests/tests_unit/test_renamePng.m
- tests/tests_workflows/test_bidsChangeSuffix.m
- tests/tests_workflows/test_bidsRename.m
- tests/tests_workflows/test_renameSegmentParameter.m
- tests/tests_workflows/test_renameUnwarpParameter.m
> [MNT] replace isfolder by isdir

- src/IO/addGitIgnore.m
- src/IO/addLicense.m
- src/IO/addReadme.m
- src/bids/initBids.m
- src/reports/LICENSE
- tests/tests_bids/test_initBids.m
> [ENH] Add CC0 license by default to all outputs

- demos/transformers/split_by_trials.m
- docs/source/bids_stats_model.md
> [DOC] add doc to link to transformations

- .circleci/config.yml
- bidspm.m
- src/IO/getData.m
- src/batches/preproc/setBatchSmoothingAnat.m
- src/bidspm.py
- src/messages/bugReport.m
- src/workflows/stats/bidsResults.m
- tests/tests_workflows/stats/test_bidsResults.m
> [ENH] use filtering of layout

- docs/source/architecture.rst
- docs/source/bids_stats_model.md
- docs/source/configuration.rst
> [DOC] update doc regarding FAST model as default

- src/workflows/bidsRename.m
- tests/tests_workflows/test_bidsRename.m
> [ENH] update rename to store original spm name of a file in metadata

- .github/workflows/tests.yml
- .github/workflows/tests_windows.yml
- src/batches/stats/setBatchFactorialDesign.m
- tools/update.sh
> [INFRA] update submodules and split windows testing

- bidspm.m
- src/utils/getFuncVoxelDims.m
- src/workflows/bidsCheckVoxelSize.m
- tests/tests_batches/test_saveMatlabBatch.m
> [FIX] Fix the way the voxel size is computed

- CHANGELOG.md
- src/batches/stats/setBatchSubjectLevelGLMSpec.m
- src/stats/subject_level/convertOnsetTsvToMat.m
- src/stats/subject_level/createAndReturnOnsetFile.m
- tests/tests_stats/subject_level/test_convertOnsetTsvToMat.m
- tests/tests_stats/subject_level/test_createAndReturnOnsetFile.m
> [FIX] exclude late events

- CHANGELOG.md
- tools/add_links_to_changlog.py
> [DOC] add links to changelog

- src/workflows/bidsCopyInputFolder.m
> [ENH] add schema arguemnt to bids copy

- bidspm.m
- src/infra/checkToolbox.m
> [FIX] use git to update MACS

- .circleci/config.yml
- .github/workflows/tests.yml
- demos/transformers/split_by_trials.m
- docs/source/bids_stats_model.md
should allow testing with macOS latest
> [MAINT] bump matlab version to test in CI and test on macOS 13 and 14

- src/IO/getData.m
- tests/tests_bids/test_getData.m
> [FIX] getData only loads anat data when requested

- src/workflows/stats/bidsResults.m
> [FIX] Get correct contrast name for bidsResults

- src/bidspm/exit_codes.json
to be used later to provide standardised errors
> [ENH] add error codes
