cpp-lln-lab/bidspm

README.md
Just a first step to make it easier in the future to write the methods section.
=> Complete boiler plate methods section of the README

README.md, batch.m, getOption.m, subfun/BIDS_RFX.m, subfun/checkDependencies.m, subfun/printCredits.m
- fix RFX getting confused with some folder names 
- add zenodo DOI to readme
- add credits in file and to prompt when running the pipeline
=> fix RFX issues and add credits

subfun/getData.m, test/dummyData/derivatives/SPM12_CPPL/sub-01/ses-01/anat/sub-01_ses-01_T1w.json, test/test_getData.m
This should fix the issue #68 but the problem is that because of the way `spm_BIDS` is coded for the moment, the json file with the anat metadata must be stored in the anat folder of the subjects and not only in the dataset root folder.
I think that if we used the `bids_matlab` toolbox instead of the `spm_BIDS` function internal to SPM we would get around this issue but this requires adding a dependency to the pipeline. I am ok with that but managing dependencies with matlab is... well... a pain.
@mohmdrezk what do you think?
=> allow getData to query only anatomical data

demos/sourceDataProcessing/batchSource.m, demos/sourceDataProcessing/getOptionSource.m, src/batches/setBatch3Dto4D.m, src/batches/setBatchGZip.m, src/defaults/checkOptionsSource.m, src/workflows/bidsGZipRawFolder.m, tests/test_checkOptionsSource.m
Very simple scripts to gzip any `.nii` file a raw folder. Any suggestion on how to make them smarter and how they are organize in the repo struct is welcome.
=> [ENH] add gzip scripts for raw folder 

src/subject_level/convertOnsetTsvToMat.m, src/subject_level/createAndReturnOnsetFile.m, tests/dummyData/models/model-vislocalizer_smdl.json
fix #197, this way the .mat files contains only the `trial_type` entries that are present in the `events` file. This way if eg responses are missing, they will not be put in the model.
(I have created this pr from the submodule of my analysis repo, it is the first so let me know if this way is correct)
=> [FIX] Missing trial_types are not added to a model specification / fixes #197

src/workflows/bidsFFX.m
in `bidsFFX` it wants to move a `.png` but due to a typo it was crashing: 
```
/bin/bash: fslmerge: command not found
Error using movefile
mv: rename
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/Pilots/RhythmBlock/code/rhythmBlock_fMRI_analysis/src/sub-008_task-RhythmBlockdesign_*
to
/Users/battal/Cerens_files/fMRI/Processed/RhythmCateg/Pilots/RhythmBlock/derivatives/cpp_spm/sub-008/stats/ffx_task-RhythmBlock/ffx_space-individual_FWHM-3/sub-008_task-RhythmBlockdesign_*:
No such file or directory
Error in bidsFFX (line 82)
movefile(['sub-', subID, '_task-', opt.taskName, 'design_*'], ...
```
=> [FIX] fix typo

demos/vismotion/batch.m
the argument order of bidsRFX is corrected. otherwise it was mixing the opt with smoothing width. It was only on `demos/vismotion`
=> [FIX] argument order of bidsFFX

src/workflows/bidsConcatBetaTmaps.m
Here it comes a hot-fix! 
I added `ffxDir` folder in the subfolder to be called. otherwise `remove-useless-betas-subfun` is crashing. 
Should fix the issue #293
=> bidsConcatBetaTmaps hoxfit for ffxDir definition in subfun

src/workflows/bidsConcatBetaTmaps.m
when i use the concat script loop through different subjects due to the deletion option is on, matlabbatch gives an error. for every subject the clean matlabbatch should be opened. that's what this fix does.
=> [FIX] adapted for looping through subjects

lib/utils/plot_power_spectra_of_GLM_residuals.m, lib/utils/resize_img.m
This is one of John Ashburner's gem.
I need for something else so I am adding it to the library.
Will merge right away as this is not code we wrote.
=> [ENH] add resize_image function to library

.gitignore, src/workflows/bidsCopyRawFolder.m, tests/createDummyDataSet.sh, tests/test_bidsCopyRawFolder.m
fixes #276 
In theory, this should not delete files from the previous task when using the same derivative folder.
=> [FIX] bidsCopy does not delete previously copied tasks

README.md, src/utils/checkDependencies.m
=> [FIX] update checks on SPM version

src/batches/preproc/setBatchRealign.m, src/subject_level/createAndReturnCounfoundMatFile.m, tests/Makefile, tests/tests_utils/test_createAndReturnCounfoundMatFile.m
=> [ENH] add possibility to limit maximum number of volumes per run in a subject level GLM

.github/workflows/tests_matlab.m, .gitignore, manualTests/test_ds114.m, manualTests/test_moae.m, miss_hit.cfg, src/IO/saveSpmScript.m, src/infra/getEnvInfo.m, tests/tests_batches/test_saveMatlabBatch.m, tests/tests_infra/test_getEnvInfo.m
=> [FIX] Misc bug squashing :bug: :skull:

src/workflows/bidsChangeSuffix.m
@marcobarilari 
Was turning out to be too annoying to incorporate a change suffix only into bidsRename (that will have to happen later) so in the meantime I am adding a small workflow to change suffixes only.
=> [ENH] Add change suffix workflow

src/batches/preproc/setBatchSegmentation.m, src/defaults/checkOptions.m, tests/utils/defaultOptions.m
Docs will be updated automatically, correct?
=> fix #545 add more options for segmentation batch

src/batches/saveMatlabBatch.m, tests/tests_batches/test_saveMatlabBatch.m
=> [ENH] only save batches as .m files

demos/MoAE/Makefile, src/bids/buildIndividualSpaceRoiFilename.m, src/workflows/bidsChangeSuffix.m, src/workflows/roi/bidsCreateROI.m, tests/.gitignore, tests/tests_unit/bids/test_buildIndividualSpaceRoiFilename.m, tests/tests_workflows/test_bidsChangeSuffix.m
=> [FIX] creates BIDS valid filename for ROIs in individual space

src/batches/preproc/setBatchSkullStripping.m, src/bids/isSkullstripped.m, src/bids/returnNameSkullstripOutput.m, src/defaults/checkOptions.m, tests/.gitignore, tests/tests_batches/preproc/test_setBatchSkullStripping.m, tests/tests_bids/test_isSkullstripped.m, tests/tests_bids/test_returnNameSkullstripOutput.m, tests/utils/defaultOptions.m
=> [ENH] skullstripping fixes and options 

src/infra/getEnvInfo.m
=> [FIX] getEnvInfo for windows

src/IO/overwriteDir.m, src/batches/saveMatlabBatch.m, src/batches/stats/setBatchFactorialDesign.m, src/group_level/findSubjectConImage.m, src/workflows/saveAndRunWorkflow.m
=> [FIX] fix printing of of path 

src/defaults/getOptionsFromModel.m, src/workflows/stats/bidsFFX.m, tests/tests_workflows/stats/test_bidsFFX.m
=> [FIX] prevent some crashes if Model.Input are not passed as arrays

src/subject_level/getFFXdir.m, tests/createDummyDataSet.sh, tests/tests_bids_model/test_getFFXdir.m, tests/tests_bids_model/test_getRFXdir.m
- use a `node` entity instead of a `desc` one for run level stats folder when using a user specified "description"
- ignore more Node.Name than just `run_level` or `dataset_level` - fixes #647 
The path will be a default one if the node name is similar to one of those (regexp actually used to remove spaces, dashes, underscores...):
```matlab
omitList = {'run'; ...
'run level'; ...
' run level '; ...
'-run-level-'; ...
'_run_level_'};
omitList = {'dataset'; ...
'dataset level'; ...
' dataset level '; ...
'-dataset-level-'; ...
'_dataset_level_'};
```
=> [FIX] make GLM path more consistent

scripts/group_rm_anova.m, src/batches/stats/setBatchFactorialDesign.m, src/subject_level/createAndReturnCounfoundMatFile.m, src/subject_level/createAndReturnOnsetFile.m, src/workflows/stats/bidsFFX.m, src/workflows/stats/bidsRFX.m
=> [FIX] onsets and confounds are saved in the proper dir when there are several tasks

src/utils/labelActivations.m, tests/dummyData/tsv_files/bug662_results_table.csv, tests/tests_unit/test_labelActivations.m
fix bug #662 
csv results file when there is no significant voxels are ignored with a warning
=> [FIX] label actiation: csv results file witrh no significant voxels are ignored with a warning

src/IO/getData.m, tests/tests_bids/test_getData.m
=> [FIX] add more explicit error message for input parsing of getData

.vscode/settings.json, docs/source/FAQ.md, docs/source/bids_stats_model.md, docs/source/usage_notes.rst, src/workflows/preproc/bidsSpatialPrepro.m
=> [DOC] update FAQ to explain how to change subject level GLM folder name

src/stats/utils/getRegressorIdx.m, src/workflows/stats/bidsConcatBetaTmaps.m, tests/tests_workflows/test_bidsConcatBetaTmaps.m
=> [FIX] report proper fold number in labelfold.tsv

bidspm.m
=> [FIX] Force copy of data from fmriprep folder even if bidspm-preproc folder exists

src/batches/stats/setBatchFactorialDesign.m, src/bids/checkColumnParticipantsTsv.m, tests/tests_bids/unit_tests/test_checkColumnParticipantsTsv.m
=> [ENH] add proper error when a column cannot be found in participants.tsv

bidspm.m
=> [FIX] skip smoothing when running bidspm prepoc in dryRun

src/batches/preproc/setBatchGenerateT1map.m, tests/tests_batches/preproc/test_setBatchGenerateT1map.m
=> [FIX] check for bids-ish and non bids metadata for T1map generation

CHANGELOG.md, demos/bayes/ds000114_run.m, demos/bayes/models/default_model.json, docs/source/dev_doc.rst, src/QA/compileScrubbingStats.m, src/bids_model/addConfoundsToDesignMatrix.m, src/bids_model/createModelFamilies.m, src/defaults/checkOptions.m, src/messages/bidspmHelp.m, tests/tests_bids/test_getAnatFilename.m, tests/tests_bids_model/test_addConfoundsToDesignMatrix.m, tests/tests_bids_model/test_createModelFamilies.m
- closes #1029
Also adds a way to create family of models to bayesian model selection
=> [ENH] Add several confound strategies to add to bids stats model

CHANGELOG.md, bidspm.m, demos/bayes/Makefile, demos/bayes/ds000114_run.m, src/cli/cliBayesModel.m, src/cli/getOptionsFromCliArgument.m, src/cli/inputParserForBayesModel.m, src/messages/bidspmHelp.m, tests/tests_slow/tests_workflows/stats/test_bidsModelSelection.m
=> [ENH] allow to run substeps of bms

src/bids_model/BidsModel.m, tests/tests_bids_model/test_bidsModel.m
reduce number of warnings thrown by BidsModel to avoid confusing users and replace them by INFO logs instead
closes #1180
=> [FIX] less warnings in bids model

CHANGELOG.md, README.md, demos/MoAE/moae_fmriprep.m, src/IO/overwriteDir.m, src/batches/stats/setBatchInformationCriteria.m, tests/tests_slow/tests_workflows/stats/test_bidsFFX.m, tests/tests_slow/tests_workflows/stats/test_bidsRFX.m
- should at least allow bidspm stats to octave on octave until things are fixed upstream
=> [FIX] skip IC from MACS toolbox for octave for now

.circleci/config.yml, .dockerignore, .github/workflows/apptainer_build.yml, .readthedocs.yml, Dockerfile, Makefile, bidspm.def, docs/Makefile, docs/source/conf.py, docs/source/demos/openneuro.md, pyproject.toml
=> [FIX] update version in container
